ci: Build and Push this package to CodeArtiact
ClearlyEnergy/BEAM-OPT pull request #8
Opened 2024-09-23 10:03 UTC by loydbanks

2024-09-23 11:48 UTC, paddatrapper requested changes
This publishes every time a push to master happens, but the version is always the same because it isn't changed on push. This needs more configuration. Either versioning is manual and this gets run on tags or versioning needs to follow semantic versioning and this gets run as part of the semantic versioning process

2024-09-25 09:05 UTC, paddatrapper commented
Please use the same sort of semantic release process we use elsewhere - https://github.com/ClearlyEnergy/BEAM/blob/develop/.github%2Fworkflows%2Fhelm-chart.yml

There are several steps:

1. Run semantic release (with appropriate release.yml configuration file)
2. If there is a new release update pyproject.toml with the new version number
3. Build the python package
4. Publish to codeartifact

2024-09-26 16:17 UTC, paddatrapper requested changes

2024-09-26 16:17 UTC, paddatrapper commented on .github/worfklows/codeartifact-deployment.yml
> +        run: ./yq -i e '.version = "${{ env.RELEASE_VERSION }}"' pyproject.toml
Yq won't work here - it's not a yaml file

2024-09-26 16:17 UTC, paddatrapper commented on .github/worfklows/codeartifact-deployment.yml
> +  publish:
This shouldn't be a separate job - it should only happen when there is a release

2024-09-26 16:17 UTC, paddatrapper commented on .github/worfklows/codeartifact-deployment.yml
> +      - name: Push changes to beam_opt repo
Remove this step - we're not pushing to another repo

2024-09-30 10:55 UTC, loydbanks commented on .github/worfklows/codeartifact-deployment.yml
> +        run: ./yq -i e '.version = "${{ env.RELEASE_VERSION }}"' pyproject.toml
https://kislyuk.github.io/yq/#toml-support, they do support toml on Yq

2024-10-04 16:21 UTC, paddatrapper approved these changes

2024-10-11 14:23 UTC, merged